// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2Uu9XBpinH6zWNwMmzN27hmJ-A2eWpM',
    appId: '1:212560735888:web:9fa0b2dafe5e17be67f215',
    messagingSenderId: '212560735888',
    projectId: 'safegate-visitor-app',
    authDomain: 'safegate-visitor-app.firebaseapp.com',
    databaseURL: 'https://safegate-visitor-app-default-rtdb.firebaseio.com',
    storageBucket: 'safegate-visitor-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrSpiykOi8rAEB3zIioZuXlJZazoUuBM',
    appId: '1:212560735888:android:5daf0368a01a5c9b67f215',
    messagingSenderId: '212560735888',
    projectId: 'safegate-visitor-app',
    databaseURL: 'https://safegate-visitor-app-default-rtdb.firebaseio.com',
    storageBucket: 'safegate-visitor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2jNcYm_tpDUUx-iROXwHSfuGB0v0Sm84',
    appId: '1:212560735888:ios:c14b66eedb6bcd1767f215',
    messagingSenderId: '212560735888',
    projectId: 'safegate-visitor-app',
    databaseURL: 'https://safegate-visitor-app-default-rtdb.firebaseio.com',
    storageBucket: 'safegate-visitor-app.firebasestorage.app',
    iosBundleId: 'com.example.safegate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2jNcYm_tpDUUx-iROXwHSfuGB0v0Sm84',
    appId: '1:212560735888:ios:c14b66eedb6bcd1767f215',
    messagingSenderId: '212560735888',
    projectId: 'safegate-visitor-app',
    databaseURL: 'https://safegate-visitor-app-default-rtdb.firebaseio.com',
    storageBucket: 'safegate-visitor-app.firebasestorage.app',
    iosBundleId: 'com.example.safegate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR2Uu9XBpinH6zWNwMmzN27hmJ-A2eWpM',
    appId: '1:212560735888:web:13e2b88171e2178f67f215',
    messagingSenderId: '212560735888',
    projectId: 'safegate-visitor-app',
    authDomain: 'safegate-visitor-app.firebaseapp.com',
    databaseURL: 'https://safegate-visitor-app-default-rtdb.firebaseio.com',
    storageBucket: 'safegate-visitor-app.firebasestorage.app',
  );

}